### ISSUE TITLE
Single Connection Refused Hangs Entire ucsmsdk

### ISSUE THREAD

**Issue by ejtbrown** [CiscoUcs/ucsmsdk#120]
Under specific circumstances, the ucsmsdk will hang. The circumstances are as follows:

1) Create a handle to something other than a fully functional UCS manager
2) Attempt to login using the handle (this correctly raises an exception)
3) Create a handle to a fully function UCS manager
4) Attempt to login using the second handle (at this point, everything hangs indefinitely)

I've tried enabling threading mode on the handles, in hopes that the improved isolation would resolve the problem - sadly, it made no difference.

**Comment by vvb** [comment]
@ejtbrown thanks for reporting this. Debugged this to be an issue with locks in a specific negative case. 
will check-in a fix later today.

**Comment by vvb** [comment]
@parag-may4 @waghswapnil this would apply to other sdks too..
