### ISSUE TITLE
Problem Launching UCS Interface

### ISSUE THREAD

**Issue by tomasvb** [CiscoUcs/ucsmsdk#133]
I have a problem logging in into the UCSM console. It worked perfect last week, but now I'm receiving errors which does not ring a bell. I already changed the JAVA_HOME variable to the right path, but still error message.
![image](https://cloud.githubusercontent.com/assets/24458551/21015753/75415748-bd63-11e6-96b7-cba7eff1f4ca.png)

The link it provides works perfect, so if I launch this in a browser, I can download the java applet.

Suggestions?

**Comment by vvb** [comment]
@TomasVB what is the output of `echo $JAVA_HOME` look like?
