### ISSUE TITLE
Enforce SSL validation

### ISSUE THREAD

**Issue by russellpope** [CiscoUcs/ucsmsdk#134]
Hey there! I would love for there to be an option to force SSL validation instead of just blindly trusting the certificate. Ideally the default operation would be to enforce with the ability to override to disable it.

**Comment by bradleyjones** [comment]
Would be great to see this as the default and an option to turn it off

**Comment by seils** [comment]
This is challenging in the current implementation because ucsmsdk is still carrying around support for Python versions < 2.7.9.

@vvb Python 2.7.9 is 4+ years old.  Can we up the minimum version requirement for ucsmsdk to 2.7.9?
