### ISSUE TITLE
Why not make arguments as list?

### ISSUE THREAD

**Issue by muzixing** [CiscoUcs/ucsmsdk#144]
Hi there,
Why not make [query_classids](https://github.com/CiscoUcs/ucsmsdk/blob/f79179f859a868798c50902bfa6c8a4cd756ba47/ucsmsdk/ucshandle.py#L260)'s arguments as a list?  It is really hard to pass the multiple class ID to method.

**Comment by vvb** [comment]
@muzixing thank you for the request. #146 will take care of this.

**Comment by muzixing** [comment]
Thank you!  However, It seems like the new version code haven't been publish. I prefer to use it by updating ucsmsdk rather than changing the code by myself.

**Comment by vvb** [comment]
@muzixing yes, it was under code review.. it is merged now.
