### ISSUE TITLE
Error launching ucs_gui_launch -Unable to use convert_to_ucs_python utility

### ISSUE THREAD

**Issue by interop-hcl** [CiscoUcs/ucsmsdk#159]
Hi ,

I have Cisco UCSMSDK library installed and I am trying to use convert_to_python utility to get the ucs scripts based on my actions in Java GUI. 
I am getting an error when doing ucs_gui_launch(handle)
TypeError: coercing to Unicode: need string or buffer, NoneType found
I have JAVA_HOME environment variable set properly.

Convert to python was previously working fine.I have upgraded UCS Manager to 3.1(3a) and noticed that "Beginning with Cisco UCS Manager Release 3.1(3a), the Cisco UCS Manager GUI is no longer available as a Java-based application"(From release notes).

Is the above error because of no Java based GUI in latest UCS 3.1(3a)? If so how do I workaround and get to use convert_to_python ?
Please advice as  this is an urgent request.
Please find below screenshot
![ucs_gui](https://user-images.githubusercontent.com/26954334/28823474-61290300-76db-11e7-9c38-6625e9f2b6bf.png)

Thanks,
Janani

**Comment by vvb** [comment]
@interop-hcl yes, the `ucs_gui_launch` and `convert_to_ucs_python` were designed for JAVA UCSM GUI.. 3.1(3a) does not support JAVA GUI and so the error.

An alternate way to do this using HTML UI is to collect and download the logs from HTML UI and feed the logs to `convert_to_ucs_python`. It will generate the python script based on the logs.
