### ISSUE TITLE
TLSv1.2 Connections Fail

### ISSUE THREAD

**Issue by seils** [CiscoUcs/ucsmsdk#164]
UCS Manager version 3.2(1d) added the ability to restrict HTTPS management connections to TLSv1.2.  The configuration option in the GUI is under:

Admin > Communication Management > Communication Services | HTTPS | Allowed SSL Protocols

With the `Only TLSv1.2` option selected, connections from ucsmsdk fail with the following error:

urllib2.URLError: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)>

**Comment by seils** [comment]
You can apply the following patch:

https://github.com/CiscoUcs/ucsmsdk/pull/165/commits/717504851712513d1fa28ff691d9b569de3b4854

I'll poke the maintainers to merge it as well.

**Comment by seils** [comment]
@vvb can you merge https://github.com/CiscoUcs/ucsmsdk/pull/165/commits/717504851712513d1fa28ff691d9b569de3b4854 ?

**Comment by vvb** [comment]
Merged!

--
Vikrant Balyan | Technical Engineering Leader | .:|:.:|:. Cisco Systems, Inc.
E: vvb@cisco.com<mailto:vvb@cisco.com> | O: +91 80 4429 5394<tel:+918044295394> | C: +91 9901 696 551<tel:+919901696551>
