### ISSUE TITLE
watch_ucs.py and UCSM 4 broken?

### ISSUE THREAD

**Issue by vallard** [CiscoUcs/ucsmsdk#178]
When running this command it looks for the file: 
```
https://10.93.130.100:443/ucsm/ucsm.jnlp?ucsmToken=91076043287825623987531
```
But this URL does not exist in UCS Manager version 4 as there is no ucsm.jnlp (that I'm aware of)

Is this supported in UCS Manager 4.0+? Thank you!

**Comment by vvb** [comment]
No, `watch_ucs.py` works only for UCSM releases where there was a JAVA based GUI. There is a different way of doing it for HTML based UI. You need to capture XML logs of the operation you perform on the UI, and then manually feed them to ConvertToPython. There are UI actions to start/stop/download XML logs.
