### ISSUE TITLE
Python3 'pyparsing' module usage has to be altered

### ISSUE THREAD

**Issue by Guru67724** [CiscoUcs/ucsmsdk#200]
While upgrading my Python environment to V3.7 (having the latest version of pyparsing) along with the ucsmsdk latest version, i have observed that pyparsing module used within ucsmsdk needs some changes to it.

Specifically in the file ucsmsdk/ucsfilter.py, line number 149, there is a usage of 'operatorPrecedence' from pyparsing module which has been deprecated in the latest version of pyparsing.

So i feel the 'operatorPrecedence' can be replaced with 'infixNotation' which has the similar behaviour.

Kindly have a look and let us know whether this can be taken up in the next version of ucsmsdk.

**Comment by vvb** [comment]
This was fixed and released.
