### ISSUE TITLE
Python 3.9 error 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'

### ISSUE THREAD

**Issue by aheath1992** [CiscoUcs/ucsmsdk#204]
### Problem
When running the ucs_service_profile_template role in Ansible I get the following error: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'. After doing some digging I found that python 3.9 has removed the getchildren method python 3.9,

### System Specifications 

- Fedora 33
- Python 3.9.0
- Ansible 2.9.15

### Request
I believe that not just this Ansible module but all UCS Ansible modules need to be checked and updated before the Enterprise OS versions of python update to 3.9 and modules stop working. Currently, RHEL and CentOS 8 version of python is 3.6.8 so there is some time, but bleeding edge systems like Fedora are starting to be effected.

**Comment by Tes3awy** [comment]
Hello @aheath1992 

Did you find any solution or workaround for this issue?

**Comment by vesposito** [comment]
For your information, ucsmsdk 0.9.12 has just been released and includes fixes for this issue to support Python 3.9

**Comment by aheath1992** [comment]
Thank you for the Update, Will close this as it has been resolved.
