### ISSUE TITLE
Admin>Device Connector>Settings not covered by ucsmsdk

### ISSUE THREAD

**Issue by MallocArray** [CiscoUcs/ucsmsdk#206]
There does not appear to be support for configuring the Device Connector in ucsmsdk currently, which prevents configuring it with the Ansible module as well.  CloudDeviceConnectorEp is the closest I've found which only can set claimed or not.

I'm needing to set DNS, NTP, and proxy for the Device Connector which is in the Settings sub-menu in the GUI

**Comment by vvb** [comment]
I don't think these settings are exposed via the UCSM object Model. I will check on this and update.
