### ISSUE TITLE
waiting for release with last changes

### ISSUE THREAD

**Issue by yamamoto52** [CiscoUcs/ucsmsdk#223]
hello, 

could you release last changes with '[Changes for pyparsing compat with 2.4.7 and 3.0; some parser cleanup](https://github.com/CiscoUcs/ucsmsdk/commit/0d17f5dddd06283d8a7c2e9803b3f3f0602958dc)' ? 

right now this change is only available from master branch

**Comment by vvb** [comment]
This was done.
