### ISSUE TITLE
query_dn('org-root',hierarchy=True) throws exception when using UCSM version 2.2(7b) 

### ISSUE THREAD

**Issue by tanmayx** [CiscoUcs/ucsmsdk#27]
query_dn('org-root',hierarchy=True) throws exception when using UCSM version 2.2(7b). 

Below is the exception -
ValueError: Invalid Value Exception - [FirmwarePackItem]: Prop <type>, Value<storage-controller-onboard-device>.

**Comment by vvb** [comment]
fix is already in - 0.9.1.1 will fix this
