### ISSUE TITLE
filter_str option for 'usr_lbl' property not working in query_children() for UCSM 3.1

### ISSUE THREAD

**Issue by tanmayx** [CiscoUcs/ucsmsdk#28]
when tried to execute below line -
query_children(in_dn='org-root', class_id='LsServer', filter_str="(usr_lbl, '_value_')", 
it returns the matched text and also the empty values.
It is observed that this happens with UCSM version 3.1.

**Comment by ragupta-git** [comment]
Duplicate Issue (Issue #29)

**Comment by vvb** [comment]
@tanmayx closing this as this is mentioned as a duplicate. please feel free to re-open if you do not agree.
