### ISSUE TITLE
filter_str options for query_children() returns invalid output for UCSM version 3.1

### ISSUE THREAD

**Issue by tanmayx** [CiscoUcs/ucsmsdk#29]
Execute the below commands - 
query_children(in_dn='org-root', class_id='LsServer', filter_str="(usr_lbl, _value_, flag='I')")
query_children(in_dn='org-root', class_id='LsServer', filter_str="(usr_lbl, _regexValue_, type='re')")
Both the commands return the matched values and also the blank values for usr_lbl

**Comment by ragupta-git** [comment]
Not an issue with sdk. Incorrect response from ucsm for method `configResolveChildren` and filter `wcard`.
Below xml request returns all the lsServer objects of which usrLbl is empty too.
```<inFilter><wcard class="lsServer" property="usrLbl" value="test" /></inFilter>```

**Comment by vvb** [comment]
@tanmayx @ragupta-git so this is an issue with backend? Can you guys tell me if this was always so, or is this is regression in UCSM 3.1 ?

**Comment by ragupta-git** [comment]
@vvb This issue is also with older version of UCSM too. Need to take this up with UCSM team.
Tanmay verified the same for version 2.2(5b) and 2.1 as well.
